version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front-docker
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: back-docker
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mongo:latest
    container_name: db-docker
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--eval",
          "db.runCommand({ ping: 1 })"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork

  # jenkins:
  #   build:
  #     context: ./jenkins
  #     dockerfile: Dockerfile
  #   container_name: jenkins
  #   restart: always
  #   user: root
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - jenkins-data:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./tmp:/usr/local/bin/docker-compose  # Adjust this path accordingly
  #   networks:
  #     - mynetwork

  # sonarqube:
  #   image: "sonarqube:9.3-community"
  #   container_name: sonarqube
  #   environment:
  #     - SONARQUBE_JDBC_USERNAME=sonarqube
  #     - SONARQUBE_JDBC_PASSWORD=sonarqube
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - mynetwork
  #   volumes:
  #     - ./sonarqube_data:/var/lib/sonarqube/data

  # traefik:
  #   image: "traefik:v2.5"
  #   container_name: traefik
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./traefik/traefik.toml:/traefik.toml
  #   networks:
  #     - mynetwork

volumes:
  data:
  # jenkins-data:

networks:
  mynetwork:
    name: mynetwork
