name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checking Docker Compose version
      run: docker-compose version

    - name: Testing frontend
      working-directory: frontend
      run: npm test

    - name: Testing backend
      working-directory: backend
      run: npm test

    - name: Show Docker Compose logs
      run: docker-compose logs
